// <auto-generated />
using System;
using ChessCoach.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChessCoach.Api.Migrations
{
    [DbContext(typeof(ChessCoachDbContext))]
    partial class ChessCoachDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("ChessCoach.Api.Data.Entities.MoveAnalysisEvent", b =>
                {
                    b.Property<long>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CentipawnLoss")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FenBefore")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlySequenceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrimaryCategory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StructuralQuality")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubCategory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TacticalEngineVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserMoveUci")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EventId");

                    b.HasIndex("GameId", "PlySequenceId")
                        .IsUnique();

                    b.HasIndex("UserId", "PrimaryCategory", "SubCategory")
                        .HasDatabaseName("idx_user_analytics_lookup");

                    b.ToTable("MoveAnalysisEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
